### PR TITLE
Injected filesystem into tf_data_utils to remove tight coupling on local filesystem

### PR DESCRIPTION
**Pull request by Samshal**
This allows loading datasets from S3 bucket or any where else training data may reside.

### CODE REVIEW

**Comment by batic** [comment]
Hi @Samshal 

Thank you for your contribution! Could you update the Conda environment file as well?

Best,
Matej

**Comment by veseln** [comment]
Thank you for the contribution! 

Just a note, I think the changes make sense, however one must be aware of the caveat that using filesystem for loading remote data might make training slower.  Locally stored npz files were used due to the fact that using remotely stored data proved to be a bottleneck when loading dataset for training, but this probably depends on the setup used, so these changes make sense.

**Comment by Samshal** [comment]
Thank you @batic and @veseln.

I understand it is better to train with data available on the local filesystem. But I noticed there was not much difference in terms of latency when using sagemaker + s3 and when there are very large quantity of data, it is much better to load them directly from the buckets to allow selecting portions of the data at random, this was my use case.

I'm not sure I understand how to update the conda environment because I did not introduce new packages, could you please explain what I need to do? @batic.

**Comment by batic** [comment]
> I'm not sure I understand how to update the conda environment because I did not introduce new packages, could you please explain what I need to do? @batic.

Nevermind, forgot we're using it as well.

**Pull request merged**
